# version: '3.8'

services:
  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - .:/app
