# --- FRONT-END DEV SETUP ---

# Specify the base image for React frontend
FROM node:18-alpine AS frontend-dev

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the working directory
COPY . .

# Expose the development server port
EXPOSE 3000

# Start the Vite development server
CMD ["npm", "run", "dev"]

