version: '3.8'  

services:
  frontend-prod:
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "80:80" 

  frontend-dev:
    build:
      context: .  
      dockerfile: Dockerfile.dev  
    ports:
      - "3000:3000"  
    volumes:
      - .:/app 
      - /app/node_modules
  